services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - target=dev
    tty: true
    volumes:
      - ./src/:/app
    ports:
      - 18080:80
        #entrypoint: tail -f /dev/null

