services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    tty: true
    volumes:
      - ./src/:/app
    ports:
      - 18080:8080
        #entrypoint: tail -f /dev/null

