on:
  push:
    branches: [ "main" ]
  pull_request:
    
name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.0'
    - uses: actions/checkout@v4
    - run: (cd src && go test ./... -coverprofile=converage.out)
    - name: report convarage
      uses: k1Low/octocov-action@v0